"""Settings — everything v1's Settings screen did, minus the half that needed
accounts.

v1's /settings (services/settings_api.py) is three cards: "My account",
"Login accounts" (add a user, set Normal/Admin) and "Blocked pages". Decision
#4 deletes the first two outright — v2 has no login, no users and no roles, so
there is nothing to manage and no role to assign. Blocked pages survives
column for column: Page, Page ID, Reason, Blocked, and the Unblock button.

The rest of this screen is the settings v1 kept scattered somewhere else and
the owner still needs:

  Appearance      the black / light theme switch (v1 put it in the topbar only)
  Worker access   the shared token the Chrome extension authenticates with,
                  generated by app/job_service.py::worker_token
  API keys        the transcription providers v1 read out of
                  services/transcribe_providers.py — Gemini, Groq, Sarvam
  Blocked pages   v1's card, plus the hidden pages the Page Analyzer hides
  Backups         v1 had six .sqlite3 snapshots in a folder and nothing that
                  knew about them; 002 added the table, this makes them
  Database        the facts /health returns, on a screen instead of in JSON
  Data version    OLD DATA / NEW DATA — which file is live, both files' row
                  counts, the switch, and the one-time "create" (app/dataset.py)

SECRETS DISCIPLINE. The three provider keys and the worker token are the only
secrets this app holds. They are never rendered in full (the worker token is
behind a collapsed disclosure because its whole purpose is to be copied into
the extension), never written to a log line, and never echoed back in a flash
message or an error — if you add a code path here that touches ``value``, it
must not end up in ``log.*`` or in ``flash()``.
"""

from __future__ import annotations

import logging
import os
import secrets as py_secrets
import sqlite3
from pathlib import Path

from flask import (
    Blueprint,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)

from .. import dataset, db
from ..time_utils import utc_now

log = logging.getLogger("adspy2.settings")

bp = Blueprint("settings", __name__)

SECTIONS: tuple[tuple[str, str, str], ...] = (
    ("appearance", "Appearance", "sun"),
    ("worker", "Worker access", "queue"),
    ("keys", "API keys", "settings"),
    ("blocked", "Blocked pages", "pages"),
    ("backups", "Backups", "report"),
    ("database", "Database", "info"),
    ("dataset", "Data version", "info"),
)
SECTION_KEYS = tuple(key for key, _, _ in SECTIONS)

# key in `settings`, label, where the provider docs call it, env fallback
API_KEYS: tuple[tuple[str, str, str], ...] = (
    ("groq_api_key", "Groq", "GROQ_API_KEY"),
    ("sarvam_api_key", "Sarvam", "SARVAM_API_KEY"),
    # Legacy: v2's transcription never calls Gemini (app/transcription.py runs
    # a "gemini" choice as Groq whisper-large-v3 — the live A/B found turbo /
    # Gemini garbled Hindi). The row stays so an old stored key can be cleared.
    ("gemini_api_key", "Gemini (legacy, not used)", "GEMINI_API_KEY"),
)

# What the "Default provider" select offers. Gemini is deliberately absent:
# a stored "gemini" value is honoured as Groq with a note in the product panel.
PROVIDERS: tuple[tuple[str, str], ...] = (
    ("groq", "Groq (whisper-large-v3)"), ("sarvam", "Sarvam (Indic)"),
)

BLOCKED_PAGE_SIZE = 25


@bp.record_once
def _ensure_session_key(state) -> None:
    app = state.app
    if not app.config.get("SECRET_KEY"):
        app.config["SECRET_KEY"] = (
            os.environ.get("ADSPY2_SECRET_KEY") or py_secrets.token_hex(32)
        )


# ---------------------------------------------------------------------------
# settings table helpers
# ---------------------------------------------------------------------------
def _get(key: str, default: str = "") -> str:
    row = db.fetch_one("SELECT value FROM settings WHERE key = ?", (key,))
    return default if row is None else str(row["value"])


def _updated_at(key: str) -> str:
    row = db.fetch_one("SELECT updated_at FROM settings WHERE key = ?", (key,))
    return "" if row is None else str(row["updated_at"])


def _set(key: str, value: str) -> None:
    with db.transaction():
        db.execute(
            """
            INSERT INTO settings(key, value, updated_at) VALUES(?,?,?)
            ON CONFLICT(key) DO UPDATE SET value = excluded.value,
                                           updated_at = excluded.updated_at
            """,
            (key, str(value), utc_now()),
        )


def mask(value: str) -> str:
    """A secret, shown the only way a secret should be: enough to recognise it,
    not enough to use it. Never returns more than the last four characters."""
    text = str(value or "").strip()
    if not text:
        return ""
    if len(text) <= 8:
        return "•" * 8
    return "•" * 8 + text[-4:]


def api_key_rows() -> list[dict]:
    rows = []
    for key, label, env_name in API_KEYS:
        stored = _get(key)
        from_env = os.environ.get(env_name, "").strip()
        rows.append(
            {
                "key": key,
                "label": label,
                "env_name": env_name,
                "configured": bool(stored),
                "masked": mask(stored),
                "updated_at": _updated_at(key) if stored else "",
                "env_fallback": bool(from_env) and not stored,
            }
        )
    return rows


# ---------------------------------------------------------------------------
# blocked + hidden pages
# ---------------------------------------------------------------------------
def blocked_pages(search: str = "", page: int = 1) -> dict:
    where, params = "", []
    if search.strip():
        where = (
            " WHERE b.page_name_snapshot LIKE ? COLLATE NOCASE"
            " OR b.platform_page_id LIKE ?"
            " OR b.reason LIKE ? COLLATE NOCASE"
        )
        needle = f"%{search.strip()}%"
        params = [needle, needle, needle]

    total_row = db.fetch_one(
        f"SELECT COUNT(*) AS n FROM blocked_pages b{where}", params
    )
    total = int(total_row["n"]) if total_row else 0
    pages = max(1, -(-total // BLOCKED_PAGE_SIZE))
    page = max(1, min(int(page), pages))
    rows = [
        dict(row)
        for row in db.fetch_all(
            f"""
            SELECT b.*, p.name AS live_name
              FROM blocked_pages b
              LEFT JOIN pages p ON p.id = b.page_id
              {where}
             ORDER BY b.created_at DESC, b.id DESC
             LIMIT ? OFFSET ?
            """,
            [*params, BLOCKED_PAGE_SIZE, (page - 1) * BLOCKED_PAGE_SIZE],
        )
    ]
    return {"rows": rows, "total": total, "page": page, "pages": pages,
            "start": 0 if not total else (page - 1) * BLOCKED_PAGE_SIZE + 1,
            "end": min(page * BLOCKED_PAGE_SIZE, total)}


def hidden_pages() -> list[dict]:
    return [
        dict(row)
        for row in db.fetch_all(
            """
            SELECT id, name, platform_page_id, active_ads, updated_at
              FROM pages WHERE is_hidden = 1
             ORDER BY name COLLATE NOCASE
             LIMIT 200
            """
        )
    ]


# ---------------------------------------------------------------------------
# backups
# ---------------------------------------------------------------------------
def backup_dir() -> Path:
    return Path(db.current_database_path()).parent / "backups"


def _sync_backups_from_disk() -> None:
    """Files first, table second. A snapshot someone made with `cp` is still a
    backup; the table exists so the card can list them, not to own them."""
    folder = backup_dir()
    if not folder.is_dir():
        return
    now = utc_now()
    try:
        found = sorted(folder.glob("*.sqlite3"))
    except OSError:  # pragma: no cover - unreadable directory
        return
    with db.transaction():
        for path in found:
            try:
                size = path.stat().st_size
            except OSError:  # pragma: no cover
                continue
            db.execute(
                """
                INSERT INTO backups(filename, size_bytes, reason, created_at)
                VALUES(?,?,'manual',?)
                ON CONFLICT(filename) DO UPDATE SET size_bytes = excluded.size_bytes
                """,
                (path.name, size, now),
            )
        # A row whose file was deleted underneath us is noise, not history.
        names = {path.name for path in found}
        for row in db.fetch_all("SELECT id, filename FROM backups"):
            if str(row["filename"]) not in names:
                db.execute("DELETE FROM backups WHERE id = ?", (int(row["id"]),))


def backup_rows() -> list[dict]:
    _sync_backups_from_disk()
    rows = [dict(row) for row in db.fetch_all(
        "SELECT * FROM backups ORDER BY created_at DESC, id DESC LIMIT 50"
    )]
    for row in rows:
        row["size_mb"] = round(int(row["size_bytes"] or 0) / 1_048_576, 1)
    return rows


# ---------------------------------------------------------------------------
# database facts
# ---------------------------------------------------------------------------
def _count(sql: str) -> int | None:
    try:
        row = db.fetch_one(sql)
    except sqlite3.Error:  # pragma: no cover
        return None
    return int(row[0]) if row else 0


def database_facts() -> dict:
    path = Path(db.current_database_path())
    conn = db.get_db()
    try:
        journal = str(conn.execute("PRAGMA journal_mode").fetchone()[0])
        page_size = int(conn.execute("PRAGMA page_size").fetchone()[0])
        page_count = int(conn.execute("PRAGMA page_count").fetchone()[0])
        foreign_keys = bool(conn.execute("PRAGMA foreign_keys").fetchone()[0])
    except sqlite3.Error as exc:  # pragma: no cover
        log.warning("could not read pragmas: %r", exc)
        journal, page_size, page_count, foreign_keys = "?", 0, 0, False

    try:
        on_disk = path.stat().st_size
    except OSError:  # pragma: no cover - :memory: or a fresh file
        on_disk = page_size * page_count

    return {
        "app": current_app.config["APP_NAME"],
        "version": current_app.config["VERSION"],
        "port": current_app.config["PORT"],
        "path": str(path),
        "size_mb": round(on_disk / 1_048_576, 1),
        "journal_mode": journal,
        "foreign_keys": foreign_keys,
        "migrations": db.applied_migrations(conn),
        "counts": {
            "pages": _count("SELECT COUNT(*) FROM pages"),
            "ads": _count("SELECT COUNT(*) FROM ads"),
            "ads_active": _count("SELECT COUNT(*) FROM ads WHERE status='active'"),
            "ad_versions": _count("SELECT COUNT(*) FROM ad_versions"),
            "products": _count("SELECT COUNT(*) FROM products"),
            "groups": _count("SELECT COUNT(*) FROM \"groups\""),
            "transcripts": _count("SELECT COUNT(*) FROM transcripts"),
            "jobs": _count("SELECT COUNT(*) FROM jobs"),
            "test_queue": _count(
                "SELECT COUNT(*) FROM test_queue_items WHERE deleted_at IS NULL"
            ),
            "shortlisted": _count("SELECT COUNT(*) FROM winner_shortlist"),
        },
    }


def _worker_token() -> str:
    """The extension's token. Delegated to the P0 service so there is exactly
    one generator; if that module is unavailable the card degrades to a notice
    rather than inventing a second token scheme."""
    try:
        from .. import job_service
    except ImportError:  # pragma: no cover
        return ""
    try:
        return str(job_service.worker_token())
    except Exception as exc:  # pragma: no cover - never leak the value
        log.warning("worker token unavailable: %s", type(exc).__name__)
        return ""


# ---------------------------------------------------------------------------
# screen
# ---------------------------------------------------------------------------
@bp.get("/settings")
def settings_page():
    section = str(request.args.get("section") or "appearance").lower()
    if section not in SECTION_KEYS:
        section = "appearance"

    context = {
        "active_nav": "settings",
        "sections": SECTIONS,
        "section": section,
        "rail": [(key, label, url_for("settings.settings_page", section=key), icon)
                 for key, label, icon in SECTIONS],
    }
    if section == "worker":
        token = _worker_token()
        context.update(token=token, token_masked=mask(token),
                       token_updated=_updated_at("worker_token"),
                       queue_paused=_get("queue_paused") == "1")
    elif section == "keys":
        context.update(api_keys=api_key_rows(),
                       providers=PROVIDERS,
                       provider=_get("transcription_provider", "groq"))
    elif section == "blocked":
        context.update(
            blocked=blocked_pages(request.args.get("q", ""),
                                  int(request.args.get("page", 1) or 1)),
            hidden=hidden_pages(),
            q=request.args.get("q", ""),
        )
    elif section == "backups":
        context.update(backups=backup_rows(), backup_dir=str(backup_dir()))
    elif section == "database":
        context.update(facts=database_facts())
    elif section == "dataset":
        context.update(
            datasets=[dataset.facts(name) for name in ("old", "new")],
            carry_over_keys=dataset.CARRY_OVER_KEYS,
        )
    return render_template("settings.html", **context)


# ---------------------------------------------------------------------------
# actions
# ---------------------------------------------------------------------------
@bp.post("/settings/worker-token/rotate")
def rotate_worker_token():
    """A new token. The extension stops working until you paste the new one in,
    which is the point: this is how you lock out a browser profile you no
    longer control."""
    _set("worker_token", py_secrets.token_urlsafe(32))
    log.info("worker token rotated")          # the event, never the value
    flash("Worker token rotated. Paste the new token into the extension.",
          "warning")
    return redirect(url_for("settings.settings_page", section="worker"))


@bp.post("/settings/api-keys")
def save_api_keys():
    """Blank means "leave it alone", so a form round-trip never wipes a key you
    could not see. The values never reach a log line or a flash message."""
    changed = []
    for key, label, _env in API_KEYS:
        value = str(request.form.get(key) or "").strip()
        if value:
            _set(key, value)
            changed.append(label)
    provider = str(request.form.get("transcription_provider") or "").strip().lower()
    if provider in {name for name, _ in PROVIDERS}:
        _set("transcription_provider", provider)

    if changed:
        log.info("api keys updated: %s", ", ".join(changed))
        flash(f"Saved {', '.join(changed)} key.", "success")
    else:
        flash("Default provider saved. Blank fields left the stored keys alone.",
              "success")
    return redirect(url_for("settings.settings_page", section="keys"))


@bp.post("/settings/api-keys/clear")
def clear_api_key():
    key = str(request.form.get("key") or "")
    labels = {name: label for name, label, _ in API_KEYS}
    if key not in labels:
        flash("Unknown API key.", "error")
        return redirect(url_for("settings.settings_page", section="keys"))
    with db.transaction():
        db.execute("DELETE FROM settings WHERE key = ?", (key,))
    log.info("api key cleared: %s", labels[key])
    flash(f"{labels[key]} key removed.", "success")
    return redirect(url_for("settings.settings_page", section="keys"))


@bp.post("/settings/blocked/<int:blocked_id>/unblock")
def unblock_page(blocked_id: int):
    row = db.fetch_one(
        "SELECT page_name_snapshot, page_id FROM blocked_pages WHERE id = ?",
        (blocked_id,),
    )
    if row is None:
        flash("That page is not blocked.", "error")
        return redirect(url_for("settings.settings_page", section="blocked"))
    with db.transaction():
        db.execute("DELETE FROM blocked_pages WHERE id = ?", (blocked_id,))
        if row["page_id"] is not None:
            db.execute(
                "UPDATE pages SET is_hidden = 0, updated_at = ? WHERE id = ?",
                (utc_now(), int(row["page_id"])),
            )
    flash(f"{row['page_name_snapshot'] or 'Page'} unblocked. Nothing was deleted.",
          "success")
    return redirect(request.form.get("next")
                    or url_for("settings.settings_page", section="blocked"))


@bp.post("/settings/pages/<int:page_id>/unhide")
def unhide_page(page_id: int):
    row = db.fetch_one("SELECT name FROM pages WHERE id = ?", (page_id,))
    if row is None:
        flash("No such page.", "error")
        return redirect(url_for("settings.settings_page", section="blocked"))
    with db.transaction():
        db.execute(
            "UPDATE pages SET is_hidden = 0, updated_at = ? WHERE id = ?",
            (utc_now(), page_id),
        )
    flash(f"{row['name']} is visible again.", "success")
    return redirect(request.form.get("next")
                    or url_for("settings.settings_page", section="blocked"))


@bp.post("/settings/backups/create")
def create_backup():
    """``VACUUM INTO`` — the only correct way to copy a live WAL database.
    Never a file copy: the -wal file holds committed pages the .sqlite3 file
    does not, so `cp` gives you a snapshot that is quietly missing writes."""
    folder = backup_dir()
    try:
        folder.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        flash(f"Could not create {folder}: {exc}", "error")
        return redirect(url_for("settings.settings_page", section="backups"))

    stamp = utc_now().replace(":", "").replace("-", "").replace("T", "-")[:15]
    # Both datasets back up into the same folder, so the name says which one
    # this snapshot is of — an OLD and a NEW snapshot must never look alike.
    prefix = f"{dataset.active()}-adspy2"
    target = folder / f"{prefix}-{stamp}.sqlite3"
    if target.exists():
        target = folder / f"{prefix}-{stamp}-{py_secrets.token_hex(2)}.sqlite3"

    try:
        # VACUUM cannot run inside a transaction; db.connect() uses
        # isolation_level=None, so this statement stands alone.
        db.get_db().execute("VACUUM INTO ?", (str(target),))
    except sqlite3.Error as exc:
        log.warning("backup failed: %r", exc)
        flash(f"Backup failed: {exc}", "error")
        return redirect(url_for("settings.settings_page", section="backups"))

    size = target.stat().st_size if target.exists() else 0
    with db.transaction():
        db.execute(
            """
            INSERT INTO backups(filename, size_bytes, reason, created_at)
            VALUES(?,?,'manual',?)
            ON CONFLICT(filename) DO UPDATE SET size_bytes = excluded.size_bytes
            """,
            (target.name, size, utc_now()),
        )
    flash(f"Backup written: {target.name} ({round(size / 1_048_576, 1)} MB).",
          "success")
    return redirect(url_for("settings.settings_page", section="backups"))


@bp.post("/settings/backups/<int:backup_id>/delete")
def delete_backup(backup_id: int):
    row = db.fetch_one("SELECT filename FROM backups WHERE id = ?", (backup_id,))
    if row is None:
        flash("No such backup.", "error")
        return redirect(url_for("settings.settings_page", section="backups"))
    target = backup_dir() / str(row["filename"])
    try:
        if target.is_file():
            target.unlink()
    except OSError as exc:
        flash(f"Could not delete {target.name}: {exc}", "error")
        return redirect(url_for("settings.settings_page", section="backups"))
    with db.transaction():
        db.execute("DELETE FROM backups WHERE id = ?", (backup_id,))
    flash(f"Deleted {row['filename']}.", "success")
    return redirect(url_for("settings.settings_page", section="backups"))


__all__ = ["bp", "mask", "database_facts", "blocked_pages", "api_key_rows"]
